-- Full Supabase setup for Code Day Penalty Shootout leaderboard
-- Username-based best score per difficulty. Run this in Supabase SQL Editor.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  name_key text,
  score integer not null,
  time integer not null,
  diff text not null,
  flag text not null
);

alter table public.leaderboard add column if not exists name_key text;

-- Old versions may have created device_id. It is not used anymore.
-- You may keep it or remove it manually later; the app will not read/display it.

drop index if exists leaderboard_device_diff_unique;
create unique index if not exists leaderboard_name_diff_unique
on public.leaderboard (name_key, diff)
where name_key is not null;

alter table public.leaderboard enable row level security;

drop policy if exists "Public can read leaderboard" on public.leaderboard;
drop policy if exists "Public can insert valid leaderboard scores" on public.leaderboard;
drop policy if exists "Public can update own device leaderboard score" on public.leaderboard;
drop policy if exists "Public can update username leaderboard score" on public.leaderboard;

create policy "Public can read leaderboard"
on public.leaderboard
for select
to anon, authenticated
using (true);

create policy "Public can insert valid leaderboard scores"
on public.leaderboard
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 20
  and name_key is not null
  and char_length(name_key) between 1 and 20
  and score between 0 and 5
  and time >= 0
  and diff in ('EASY', 'MEDIUM', 'HARD')
  and char_length(flag) between 1 and 8
);

create policy "Public can update username leaderboard score"
on public.leaderboard
for update
to anon, authenticated
using (name_key is not null)
with check (
  char_length(name) between 1 and 20
  and name_key is not null
  and char_length(name_key) between 1 and 20
  and score between 0 and 5
  and time >= 0
  and diff in ('EASY', 'MEDIUM', 'HARD')
  and char_length(flag) between 1 and 8
);

-- Optional: if you already have old scores, you can backfill name_key once:
-- update public.leaderboard set name_key = lower(trim(name)) where name_key is null;
