-- Full Supabase setup for Code Day Penalty Shootout leaderboard
-- Run this in Supabase SQL Editor for the SAME project used in the HTML file.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  time integer not null,
  diff text not null,
  flag text not null
);

alter table public.leaderboard enable row level security;

-- Keep old score data, but replace policies so the browser can read/insert valid scores.
drop policy if exists "Public can read leaderboard" on public.leaderboard;
drop policy if exists "Public can insert valid leaderboard scores" on public.leaderboard;

create policy "Public can read leaderboard"
on public.leaderboard
for select
to anon, authenticated
using (true);

create policy "Public can insert valid leaderboard scores"
on public.leaderboard
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 20
  and score between 0 and 5
  and time >= 0
  and diff in ('EASY', 'MEDIUM', 'HARD')
  and char_length(flag) between 1 and 8
);

-- Optional sanity check after running:
-- select * from public.leaderboard order by score desc, time asc limit 8;
